from backend.services import pdf_export


def test_generate_pdf_endpoint_returns_pdf_bytes(client, monkeypatch, analysis_payload):
    monkeypatch.setattr(
        pdf_export,
        "generate_combined_pdf",
        lambda html_docs: b"%PDF-1.4\n% generated by test\n%%EOF",
    )

    response = client.post("/api/v1/generate-pdf", json=analysis_payload)

    assert response.status_code == 200, response.text
    assert response.headers["content-type"] == "application/pdf"
    assert response.content.startswith(b"%PDF-")
